# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: []

default_install_hook_types:
  - pre-commit
  - commit-msg

fail_fast: true

repos:
- repo: https://github.com/ainnoot/commit-message-pre-commit
  rev: 0.3.1
  hooks:
      - id: commit-message-check

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        stages: [ pre-commit ]

    -   id: end-of-file-fixer
        stages: [ pre-commit ]

    -   id: check-yaml
        stages: [ pre-commit ]

    -   id: check-added-large-files
        stages: [ pre-commit ]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
    -   id: ruff-format
        name: Auto-format code with ruff
        stages: [ pre-commit ]

    -   id: ruff
        name: Lint checks with ruff
        stages: [ pre-commit ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
        name: Type-checking with mypy
        stages: [ pre-commit ]
