# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: []

default_install_hook_types:
  - pre-commit
  - commit-msg

fail_fast: true



repos:
- repo: local
  hooks:
      - id: commit-msg
        name: validate commit-msg
        language: python
        language_version: "3.12"
        entry: python3 .hooks/commit-msg
        stages:
            - commit-msg

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
    -   id: ruff-format
        name: Auto-format code with ruff
        stage: pre-commit

    -   id: ruff
        name: Lint checks with ruff

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
